import { COLORS } from "@/utils/enum";
import { roboto } from "@/utils/fonts";
import { loginTextField } from "@/utils/styles";
import {
  Box,
  Card,
  Container,
  Grid2,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import loginImage from "@/login-image.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          // background: " #4b79a1",
          // backgroundImage: "linear-gradient(to right, #4b79a1, #283e51)",
          height: "100vh",
        }}
      >
        <Grid2 container>
          <Grid2 size={8}>
            <Box
              sx={{
                backgroundImage: `url(${loginImage.src})`,
                height: "100vh",
                backgroundPosition: "center",
                backgroundSize: "cover",
                backgroundRepeat: "no-repeat",
              }}
            ></Box>
          </Grid2>
          <Grid2 size={4}>
            <Box sx={{ p: 2 }}></Box>
          </Grid2>
        </Grid2>
      </Box>
    </>
  );
}
