import loginImage from "@/login-image.jpg";
import { Box, Container, Grid2 } from "@mui/material";
import Head from "next/head";
import Login from "./components/Login";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          // background: " #4b79a1",
          // backgroundImage: "linear-gradient(to right, #4b79a1, #283e51)",
          height: "100vh",
        }}
      >
        <Grid2 container>
          <Grid2 size={8}>
            <Box
              sx={{
                backgroundImage: `url(${loginImage.src})`,
                height: "100vh",
                backgroundPosition: "center",
                backgroundSize: "cover",
                backgroundRepeat: "no-repeat",
              }}
            ></Box>
          </Grid2>
          <Grid2 size={4}>
            <Box
              sx={{
                p: 2,
                height: "100vh",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Container>
                <Login />
              </Container>
            </Box>
          </Grid2>
        </Grid2>
      </Box>
    </>
  );
}
